[2025-03-20 18:00:08,204] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:05:08,405] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:10:08,584] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:11:20,985] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Session key updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2483)
[2025-03-20 18:20:08,835] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:25:09,013] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:30:09,216] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:35:09,409] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:40:09,604] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:44:51,770] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:44:51 +0000] "GET /connectors HTTP/1.1" 200 35 "-" "curl/8.5.0" 4 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:45:09,793] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:45:11,047] INFO Successfully processed removal of connector 'mysql-sink-bluesky' (org.apache.kafka.connect.storage.KafkaConfigBackingStore:1003)
[2025-03-20 18:45:11,047] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Connector mysql-sink-bluesky config removed (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2412)
[2025-03-20 18:45:11,047] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Handling connector-only config update by stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.distributed.DistributedHerder:716)
[2025-03-20 18:45:11,047] INFO [mysql-sink-bluesky|worker] Stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:45:11,047] INFO [mysql-sink-bluesky|worker] Scheduled shutdown for WorkerConnector{id=mysql-sink-bluesky} (org.apache.kafka.connect.runtime.WorkerConnector:294)
[2025-03-20 18:45:11,049] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:45:11 +0000] "DELETE /connectors/mysql-sink-bluesky HTTP/1.1" 204 0 "-" "curl/8.5.0" 13 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:45:11,049] INFO [mysql-sink-bluesky|worker] Completed shutdown for WorkerConnector{id=mysql-sink-bluesky} (org.apache.kafka.connect.runtime.WorkerConnector:314)
[2025-03-20 18:45:11,050] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:45:11,050] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:45:11,052] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=16, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:45:11,057] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=16, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:45:11,058] INFO [mysql-sink-bluesky|worker] Stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:45:11,059] WARN [mysql-sink-bluesky|worker] Ignoring stop request for unowned connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:454)
[2025-03-20 18:45:11,059] INFO [mysql-sink-bluesky|task-0] Stopping task mysql-sink-bluesky-0 (org.apache.kafka.connect.runtime.Worker:1047)
[2025-03-20 18:45:11,059] WARN [mysql-sink-bluesky|worker] Ignoring await stop request for non-present connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:475)
[2025-03-20 18:45:11,061] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished stopping tasks in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2708)
[2025-03-20 18:45:11,068] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished flushing status backing store in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2729)
[2025-03-20 18:45:11,068] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 16 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=42, connectorIds=[bluesky-AI], taskIds=[bluesky-AI-0], revokedConnectorIds=[mysql-sink-bluesky], revokedTaskIds=[mysql-sink-bluesky-0], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:45:11,069] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 42 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:45:11,069] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:45:11,069] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:45:11,069] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:45:11,070] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=17, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:45:11,073] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=17, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:45:11,074] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 17 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=42, connectorIds=[bluesky-AI], taskIds=[bluesky-AI-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:45:11,074] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 42 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:45:11,074] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:45:13,449] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:45:13 +0000] "GET /connectors HTTP/1.1" 200 14 "-" "curl/8.5.0" 3 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:48:46,514] INFO AbstractConfig values: 
 (org.apache.kafka.common.config.AbstractConfig:372)
[2025-03-20 18:48:46,519] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Connector mysql-sink-bluesky config updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2425)
[2025-03-20 18:48:46,520] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:48:46,520] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:48:46,521] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:48:46 +0000] "POST /connectors HTTP/1.1" 201 790 "-" "curl/8.5.0" 11 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:48:46,522] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=18, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:48:46,525] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=18, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:48:46,525] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 18 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=43, connectorIds=[mysql-sink-bluesky, bluesky-AI], taskIds=[bluesky-AI-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:48:46,525] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 43 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:48:46,526] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2077)
[2025-03-20 18:48:46,526] INFO [mysql-sink-bluesky|worker] Creating connector mysql-sink-bluesky of type io.confluent.connect.jdbc.JdbcSinkConnector (org.apache.kafka.connect.runtime.Worker:312)
[2025-03-20 18:48:46,526] INFO [mysql-sink-bluesky|worker] SinkConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.SinkConnectorConfig:372)
[2025-03-20 18:48:46,527] INFO [mysql-sink-bluesky|worker] EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	transforms.ReplaceFieldNames.blacklist = null
	transforms.ReplaceFieldNames.exclude = []
	transforms.ReplaceFieldNames.include = []
	transforms.ReplaceFieldNames.negate = false
	transforms.ReplaceFieldNames.predicate = null
	transforms.ReplaceFieldNames.renames = []
	transforms.ReplaceFieldNames.type = class org.apache.kafka.connect.transforms.ReplaceField$Value
	transforms.ReplaceFieldNames.whitelist = [uri, cid, text, createdAt, handle, displayName, avatar]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:372)
[2025-03-20 18:48:46,528] INFO [mysql-sink-bluesky|worker] Instantiated connector mysql-sink-bluesky with version 10.8.1 of type class io.confluent.connect.jdbc.JdbcSinkConnector (org.apache.kafka.connect.runtime.Worker:334)
[2025-03-20 18:48:46,528] INFO [mysql-sink-bluesky|worker] Finished creating connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:355)
[2025-03-20 18:48:46,529] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:48:46,530] INFO SinkConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.SinkConnectorConfig:372)
[2025-03-20 18:48:46,531] INFO EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	transforms.ReplaceFieldNames.blacklist = null
	transforms.ReplaceFieldNames.exclude = []
	transforms.ReplaceFieldNames.include = []
	transforms.ReplaceFieldNames.negate = false
	transforms.ReplaceFieldNames.predicate = null
	transforms.ReplaceFieldNames.renames = []
	transforms.ReplaceFieldNames.type = class org.apache.kafka.connect.transforms.ReplaceField$Value
	transforms.ReplaceFieldNames.whitelist = [uri, cid, text, createdAt, handle, displayName, avatar]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:372)
[2025-03-20 18:48:46,531] INFO [mysql-sink-bluesky|worker] Setting task configurations for 1 workers. (io.confluent.connect.jdbc.JdbcSinkConnector:51)
[2025-03-20 18:48:46,546] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Tasks [mysql-sink-bluesky-0] configs updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2440)
[2025-03-20 18:48:46,546] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:48:46,546] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:48:46,547] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=19, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:48:46,549] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=19, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:48:46,549] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 19 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=45, connectorIds=[mysql-sink-bluesky, bluesky-AI], taskIds=[mysql-sink-bluesky-0, bluesky-AI-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:48:46,549] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 45 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:48:46,550] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting task mysql-sink-bluesky-0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2002)
[2025-03-20 18:48:46,550] INFO [mysql-sink-bluesky|task-0] Creating task mysql-sink-bluesky-0 (org.apache.kafka.connect.runtime.Worker:645)
[2025-03-20 18:48:46,551] INFO [mysql-sink-bluesky|task-0] ConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	transforms = [ReplaceFieldNames]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig:372)
[2025-03-20 18:48:46,552] INFO [mysql-sink-bluesky|task-0] EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	transforms = [ReplaceFieldNames]
	transforms.ReplaceFieldNames.blacklist = null
	transforms.ReplaceFieldNames.exclude = []
	transforms.ReplaceFieldNames.include = []
	transforms.ReplaceFieldNames.negate = false
	transforms.ReplaceFieldNames.predicate = null
	transforms.ReplaceFieldNames.renames = []
	transforms.ReplaceFieldNames.type = class org.apache.kafka.connect.transforms.ReplaceField$Value
	transforms.ReplaceFieldNames.whitelist = [uri, cid, text, createdAt, handle, displayName, avatar]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:372)
[2025-03-20 18:48:46,552] INFO [mysql-sink-bluesky|task-0] TaskConfig values: 
	task.class = class io.confluent.connect.jdbc.sink.JdbcSinkTask
 (org.apache.kafka.connect.runtime.TaskConfig:372)
[2025-03-20 18:48:46,552] INFO [mysql-sink-bluesky|task-0] Instantiated task mysql-sink-bluesky-0 with version 10.8.1 of type io.confluent.connect.jdbc.sink.JdbcSinkTask (org.apache.kafka.connect.runtime.Worker:664)
[2025-03-20 18:48:46,552] INFO [mysql-sink-bluesky|task-0] StringConverterConfig values: 
	converter.encoding = UTF-8
	converter.type = key
 (org.apache.kafka.connect.storage.StringConverterConfig:372)
[2025-03-20 18:48:46,552] INFO [mysql-sink-bluesky|task-0] JsonConverterConfig values: 
	converter.type = value
	decimal.format = BASE64
	replace.null.with.default = true
	schemas.cache.size = 1000
	schemas.enable = true
 (org.apache.kafka.connect.json.JsonConverterConfig:372)
[2025-03-20 18:48:46,553] INFO [mysql-sink-bluesky|task-0] Set up the key converter class org.apache.kafka.connect.storage.StringConverter for task mysql-sink-bluesky-0 using the connector config (org.apache.kafka.connect.runtime.Worker:679)
[2025-03-20 18:48:46,553] INFO [mysql-sink-bluesky|task-0] Set up the value converter class org.apache.kafka.connect.json.JsonConverter for task mysql-sink-bluesky-0 using the connector config (org.apache.kafka.connect.runtime.Worker:685)
[2025-03-20 18:48:46,553] INFO [mysql-sink-bluesky|task-0] Set up the header converter class org.apache.kafka.connect.storage.SimpleHeaderConverter for task mysql-sink-bluesky-0 using the worker config (org.apache.kafka.connect.runtime.Worker:690)
[2025-03-20 18:48:46,554] WARN [mysql-sink-bluesky|task-0] Configuration key whitelist is deprecated and may be removed in the future.  Please update your configuration to use include instead. (org.apache.kafka.common.utils.ConfigUtils:113)
[2025-03-20 18:48:46,554] INFO [mysql-sink-bluesky|task-0] Initializing: org.apache.kafka.connect.runtime.TransformationChain{org.apache.kafka.connect.transforms.ReplaceField$Value} (org.apache.kafka.connect.runtime.Worker:1794)
[2025-03-20 18:48:46,554] INFO [mysql-sink-bluesky|task-0] SinkConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.SinkConnectorConfig:372)
[2025-03-20 18:48:46,555] INFO [mysql-sink-bluesky|task-0] EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSinkConnector
	errors.deadletterqueue.context.headers.enable = false
	errors.deadletterqueue.topic.name = 
	errors.deadletterqueue.topic.replication.factor = 3
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = class org.apache.kafka.connect.storage.StringConverter
	name = mysql-sink-bluesky
	predicates = []
	tasks.max = 1
	tasks.max.enforce = true
	topics = [bluesky_ai]
	topics.regex = 
	transforms = [ReplaceFieldNames]
	transforms.ReplaceFieldNames.blacklist = null
	transforms.ReplaceFieldNames.exclude = []
	transforms.ReplaceFieldNames.include = []
	transforms.ReplaceFieldNames.negate = false
	transforms.ReplaceFieldNames.predicate = null
	transforms.ReplaceFieldNames.renames = []
	transforms.ReplaceFieldNames.type = class org.apache.kafka.connect.transforms.ReplaceField$Value
	transforms.ReplaceFieldNames.whitelist = [uri, cid, text, createdAt, handle, displayName, avatar]
	value.converter = class org.apache.kafka.connect.json.JsonConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:372)
[2025-03-20 18:48:46,555] INFO [mysql-sink-bluesky|task-0] ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.include.jmx.reporter = true
	auto.offset.reset = earliest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = connector-consumer-mysql-sink-bluesky-0
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	enable.metrics.push = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = connect-mysql-sink-bluesky
	group.instance.id = null
	group.protocol = classic
	group.remote.assignor = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	internal.throw.on.fetch.stable.offset.unsupported = false
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metadata.recovery.strategy = none
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor, class org.apache.kafka.clients.consumer.CooperativeStickyAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.max.ms = 1000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 45000
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 (org.apache.kafka.clients.consumer.ConsumerConfig:372)
[2025-03-20 18:48:46,556] INFO [mysql-sink-bluesky|task-0] initializing Kafka metrics collector (org.apache.kafka.common.telemetry.internals.KafkaMetricsCollector:269)
[2025-03-20 18:48:46,559] INFO [mysql-sink-bluesky|task-0] These configurations '[metrics.context.connect.kafka.cluster.id, metrics.context.connect.group.id]' were supplied but are not used yet. (org.apache.kafka.clients.consumer.ConsumerConfig:381)
[2025-03-20 18:48:46,560] INFO [mysql-sink-bluesky|task-0] Kafka version: 3.8.1 (org.apache.kafka.common.utils.AppInfoParser:124)
[2025-03-20 18:48:46,560] INFO [mysql-sink-bluesky|task-0] Kafka commitId: 70d6ff42debf7e17 (org.apache.kafka.common.utils.AppInfoParser:125)
[2025-03-20 18:48:46,560] INFO [mysql-sink-bluesky|task-0] Kafka startTimeMs: 1742492926560 (org.apache.kafka.common.utils.AppInfoParser:126)
[2025-03-20 18:48:46,561] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Subscribed to topic(s): bluesky_ai (org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer:476)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] Starting JDBC Sink task (io.confluent.connect.jdbc.sink.JdbcSinkTask:51)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] JdbcSinkConfig values: 
	auto.create = true
	auto.evolve = true
	batch.size = 3000
	connection.attempts = 3
	connection.backoff.ms = 10000
	connection.password = [hidden]
	connection.url = jdbc:mysql://localhost/task6
	connection.user = root
	date.timezone = DB_TIMEZONE
	db.timezone = UTC
	delete.enabled = false
	dialect.name = 
	fields.whitelist = []
	insert.mode = insert
	jdbc.credentials.provider.class = class io.confluent.connect.jdbc.util.DefaultJdbcCredentialsProvider
	max.retries = 10
	mssql.use.merge.holdlock = true
	pk.fields = []
	pk.mode = none
	quote.sql.identifiers = ALWAYS
	replace.null.with.default = true
	retry.backoff.ms = 3000
	table.name.format = bluesky
	table.types = [TABLE]
	trim.sensitive.log = false
 (io.confluent.connect.jdbc.sink.JdbcSinkConfig:372)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:46,562] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:46,563] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:46,563] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:46,563] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:46,563] INFO [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:324)
[2025-03-20 18:48:46,564] INFO [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} Executing sink task (org.apache.kafka.connect.runtime.WorkerSinkTask:210)
[2025-03-20 18:48:46,569] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Cluster ID: jVS0nPZPQGOqjEs5fW_ykA (org.apache.kafka.clients.Metadata:364)
[2025-03-20 18:48:46,571] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Discovered group coordinator carlos-desktop:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:936)
[2025-03-20 18:48:46,572] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] (Re-)joining group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:604)
[2025-03-20 18:48:46,575] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Request joining group due to: need to re-join with the given member-id: connector-consumer-mysql-sink-bluesky-0-7722eb09-99bb-47a0-869a-394c5f0b0fb7 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1102)
[2025-03-20 18:48:46,575] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] (Re-)joining group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:604)
[2025-03-20 18:48:46,577] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Successfully joined group with generation Generation{generationId=1, memberId='connector-consumer-mysql-sink-bluesky-0-7722eb09-99bb-47a0-869a-394c5f0b0fb7', protocol='range'} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:665)
[2025-03-20 18:48:46,577] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Finished assignment for group at generation 1: {connector-consumer-mysql-sink-bluesky-0-7722eb09-99bb-47a0-869a-394c5f0b0fb7=Assignment(partitions=[bluesky_ai-0])} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:663)
[2025-03-20 18:48:46,580] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Successfully synced group in generation Generation{generationId=1, memberId='connector-consumer-mysql-sink-bluesky-0-7722eb09-99bb-47a0-869a-394c5f0b0fb7', protocol='range'} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:842)
[2025-03-20 18:48:46,580] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Notifying assignor about the new Assignment(partitions=[bluesky_ai-0]) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:323)
[2025-03-20 18:48:46,581] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Adding newly assigned partitions: bluesky_ai-0 (org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker:57)
[2025-03-20 18:48:46,582] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Found no committed offset for partition bluesky_ai-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1506)
[2025-03-20 18:48:46,584] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Resetting offset for partition bluesky_ai-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[carlos-desktop:9092 (id: 0 rack: null)], epoch=0}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState:398)
[2025-03-20 18:48:46,639] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:46,639] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:46,674] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:46,702] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:46,723] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:46,725] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:47,025] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:47,026] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:47,026] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=10 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:47,027] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:47,028] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:47,028] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:48:50,040] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:50,040] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:50,055] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:50,059] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:50,069] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:50,072] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:50,130] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:50,131] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:50,131] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=9 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:50,132] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:50,132] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:50,132] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:50,133] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:50,133] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:50,133] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:50,133] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:50,133] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:48:53,145] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:53,145] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:53,157] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:53,160] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:53,168] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:53,171] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:53,222] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:53,222] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:53,223] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=8 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:53,224] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:53,225] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:53,225] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:48:55,747] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:48:55 +0000] "GET /connectors HTTP/1.1" 200 35 "-" "curl/8.5.0" 2 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:48:56,237] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:56,237] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:56,252] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:56,254] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:56,262] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:56,265] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:56,306] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:56,307] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:56,307] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=7 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:56,308] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:56,308] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:48:56,569] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:56,569] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:56,581] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:56,582] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:56,590] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:56,592] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:56,636] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:56,636] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:56,636] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=6 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:56,637] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:56,637] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:56,637] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:56,638] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:56,638] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:56,638] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:56,638] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:56,638] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:48:59,648] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:48:59,648] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:48:59,659] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:48:59,662] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:48:59,668] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:48:59,670] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:48:59,710] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:59,711] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:48:59,711] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=5 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:48:59,712] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:48:59,712] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:59,713] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:59,713] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:48:59,713] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:48:59,713] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:48:59,713] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:48:59,713] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:02,723] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:49:02,723] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:49:02,736] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:49:02,738] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:49:02,745] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:49:02,747] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:49:02,781] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:02,781] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:49:02,782] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=4 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:02,782] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:49:02,782] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:02,783] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:02,783] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:02,783] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:02,783] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:49:02,783] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:49:02,783] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:05,792] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:49:05,793] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:49:05,804] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:49:05,809] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:49:05,817] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:49:05,819] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:49:05,852] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:05,853] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:49:05,853] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=3 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:49:05,854] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:49:05,854] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:06,647] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:49:06,648] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:49:06,661] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:49:06,663] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:49:06,670] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:49:06,672] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:49:06,704] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:06,705] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:49:06,705] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=2 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:49:06,706] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:49:06,706] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:09,716] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:49:09,716] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:49:09,729] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:49:09,730] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:49:09,736] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:49:09,739] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:49:09,776] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:09,776] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:49:09,776] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=1 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:09,777] INFO [mysql-sink-bluesky|task-0] Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask:65)
[2025-03-20 18:49:09,777] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:09,777] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:09,777] INFO [mysql-sink-bluesky|task-0] Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:171)
[2025-03-20 18:49:09,778] INFO [mysql-sink-bluesky|task-0] Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects:174)
[2025-03-20 18:49:09,778] INFO [mysql-sink-bluesky|task-0] Initializing writer using SQL dialect: MySqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:72)
[2025-03-20 18:49:09,778] INFO [mysql-sink-bluesky|task-0] JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask:74)
[2025-03-20 18:49:09,778] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:624)
org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:12,786] INFO [mysql-sink-bluesky|task-0] JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter:57)
[2025-03-20 18:49:12,787] INFO [mysql-sink-bluesky|task-0] Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider:64)
[2025-03-20 18:49:12,797] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for existence of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:602)
[2025-03-20 18:49:12,799] INFO [mysql-sink-bluesky|task-0] Using MySql dialect TABLE "task6"."bluesky" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:610)
[2025-03-20 18:49:12,807] INFO [mysql-sink-bluesky|task-0] Checking MySql dialect for type of TABLE "task6"."bluesky" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect:897)
[2025-03-20 18:49:12,809] INFO [mysql-sink-bluesky|task-0] Setting metadata for table "task6"."bluesky" to Table{name='"task6"."bluesky"', type=TABLE columns=[Column{'createdAt', isPrimaryKey=false, allowsNull=false, sqlType=DATETIME}, Column{'text', isPrimaryKey=false, allowsNull=false, sqlType=TEXT}, Column{'cid', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'uri', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'avatar', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}, Column{'handle', isPrimaryKey=false, allowsNull=false, sqlType=VARCHAR}, Column{'displayName', isPrimaryKey=false, allowsNull=true, sqlType=VARCHAR}]} (io.confluent.connect.jdbc.util.TableDefinitions:64)
[2025-03-20 18:49:12,843] ERROR [mysql-sink-bluesky|task-0] Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter:89)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:12,844] INFO [mysql-sink-bluesky|task-0] Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter:92)
[2025-03-20 18:49:12,844] WARN [mysql-sink-bluesky|task-0] Write of 129 records failed, remainingRetries=0 (io.confluent.connect.jdbc.sink.JdbcSinkTask:102)
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:214)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:885)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:466)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:858)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:108)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:77)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Field 'uri' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:990)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1168)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	... 19 more
[2025-03-20 18:49:12,844] ERROR [mysql-sink-bluesky|task-0] Failing task after exhausting retries; encountered 2 exceptions on last write attempt. For complete details on each exception, please enable DEBUG logging. (io.confluent.connect.jdbc.sink.JdbcSinkTask:124)
[2025-03-20 18:49:12,845] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value
 (org.apache.kafka.connect.runtime.WorkerSinkTask:633)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:133)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:12,845] ERROR [mysql-sink-bluesky|task-0] WorkerSinkTask{id=mysql-sink-bluesky-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:233)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:635)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:133)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
	... 11 more
Caused by: java.sql.SQLException: Exception chain:
java.sql.BatchUpdateException: Field 'uri' doesn't have a default value
java.sql.SQLException: Field 'uri' doesn't have a default value

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
	... 12 more
[2025-03-20 18:49:12,845] INFO [mysql-sink-bluesky|task-0] Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask:178)
[2025-03-20 18:49:12,846] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Revoke previously assigned partitions bluesky_ai-0 (org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker:79)
[2025-03-20 18:49:12,847] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] The pause flag in partitions [bluesky_ai-0] will be removed due to revocation. (org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker:83)
[2025-03-20 18:49:12,847] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Member connector-consumer-mysql-sink-bluesky-0-7722eb09-99bb-47a0-869a-394c5f0b0fb7 sending LeaveGroup request to coordinator carlos-desktop:9092 (id: 2147483647 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1173)
[2025-03-20 18:49:12,847] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1055)
[2025-03-20 18:49:12,847] INFO [mysql-sink-bluesky|task-0] [Consumer clientId=connector-consumer-mysql-sink-bluesky-0, groupId=connect-mysql-sink-bluesky] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1102)
[2025-03-20 18:49:12,851] INFO [mysql-sink-bluesky|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:49:12,852] INFO [mysql-sink-bluesky|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:49:12,852] INFO [mysql-sink-bluesky|task-0] Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:49:12,852] INFO [mysql-sink-bluesky|task-0] Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:49:12,855] INFO [mysql-sink-bluesky|task-0] App info kafka.consumer for connector-consumer-mysql-sink-bluesky-0 unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:55:10,073] INFO [AdminClient clientId=connect-cluster-shared-admin] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:1017)
[2025-03-20 18:57:07,725] INFO Successfully processed removal of connector 'mysql-sink-bluesky' (org.apache.kafka.connect.storage.KafkaConfigBackingStore:1003)
[2025-03-20 18:57:07,725] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Connector mysql-sink-bluesky config removed (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2412)
[2025-03-20 18:57:07,726] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Handling connector-only config update by stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.distributed.DistributedHerder:716)
[2025-03-20 18:57:07,726] INFO [mysql-sink-bluesky|worker] Stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:57:07,726] INFO [mysql-sink-bluesky|worker] Scheduled shutdown for WorkerConnector{id=mysql-sink-bluesky} (org.apache.kafka.connect.runtime.WorkerConnector:294)
[2025-03-20 18:57:07,726] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:57:07 +0000] "DELETE /connectors/mysql-sink-bluesky HTTP/1.1" 204 0 "-" "curl/8.5.0" 7 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:57:07,726] INFO [mysql-sink-bluesky|worker] Completed shutdown for WorkerConnector{id=mysql-sink-bluesky} (org.apache.kafka.connect.runtime.WorkerConnector:314)
[2025-03-20 18:57:07,727] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:57:07,728] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:57:07,730] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=20, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:57:07,733] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=20, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:57:07,734] INFO [mysql-sink-bluesky|worker] Stopping connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:57:07,734] WARN [mysql-sink-bluesky|worker] Ignoring stop request for unowned connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:454)
[2025-03-20 18:57:07,734] WARN [mysql-sink-bluesky|worker] Ignoring await stop request for non-present connector mysql-sink-bluesky (org.apache.kafka.connect.runtime.Worker:475)
[2025-03-20 18:57:07,734] INFO [mysql-sink-bluesky|task-0] Stopping task mysql-sink-bluesky-0 (org.apache.kafka.connect.runtime.Worker:1047)
[2025-03-20 18:57:07,735] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished stopping tasks in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2708)
[2025-03-20 18:57:07,740] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished flushing status backing store in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2729)
[2025-03-20 18:57:07,741] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 20 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=47, connectorIds=[bluesky-AI], taskIds=[bluesky-AI-0], revokedConnectorIds=[mysql-sink-bluesky], revokedTaskIds=[mysql-sink-bluesky-0], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:57:07,741] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 47 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:57:07,742] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:57:07,742] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:57:07,742] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:57:07,744] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=21, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:57:07,746] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=21, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:57:07,746] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 21 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=47, connectorIds=[bluesky-AI], taskIds=[bluesky-AI-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:57:07,746] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 47 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:57:07,747] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:57:23,518] INFO Successfully processed removal of connector 'bluesky-AI' (org.apache.kafka.connect.storage.KafkaConfigBackingStore:1003)
[2025-03-20 18:57:23,518] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Connector bluesky-AI config removed (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2412)
[2025-03-20 18:57:23,519] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Handling connector-only config update by stopping connector bluesky-AI (org.apache.kafka.connect.runtime.distributed.DistributedHerder:716)
[2025-03-20 18:57:23,519] INFO [bluesky-AI|worker] Stopping connector bluesky-AI (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:57:23,519] INFO [bluesky-AI|worker] Scheduled shutdown for WorkerConnector{id=bluesky-AI} (org.apache.kafka.connect.runtime.WorkerConnector:294)
[2025-03-20 18:57:23,519] INFO [bluesky-AI|worker] Stopping connector (uk.co.dalelane.kafkaconnect.bluesky.source.BlueskySourceConnector:68)
[2025-03-20 18:57:23,519] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:57:23 +0000] "DELETE /connectors/bluesky-AI HTTP/1.1" 204 0 "-" "curl/8.5.0" 6 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:57:23,521] INFO [bluesky-AI|worker] Completed shutdown for WorkerConnector{id=bluesky-AI} (org.apache.kafka.connect.runtime.WorkerConnector:314)
[2025-03-20 18:57:23,522] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:57:23,522] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:57:23,524] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=22, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:57:23,526] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=22, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:57:23,527] INFO [bluesky-AI|worker] Stopping connector bluesky-AI (org.apache.kafka.connect.runtime.Worker:451)
[2025-03-20 18:57:23,527] WARN [bluesky-AI|worker] Ignoring stop request for unowned connector bluesky-AI (org.apache.kafka.connect.runtime.Worker:454)
[2025-03-20 18:57:23,527] INFO [bluesky-AI|task-0] Stopping task bluesky-AI-0 (org.apache.kafka.connect.runtime.Worker:1047)
[2025-03-20 18:57:23,527] WARN [bluesky-AI|worker] Ignoring await stop request for non-present connector bluesky-AI (org.apache.kafka.connect.runtime.Worker:475)
[2025-03-20 18:57:23,529] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished stopping tasks in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2708)
[2025-03-20 18:57:23,532] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished flushing status backing store in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2729)
[2025-03-20 18:57:23,532] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 22 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=49, connectorIds=[], taskIds=[], revokedConnectorIds=[bluesky-AI], revokedTaskIds=[bluesky-AI-0], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:57:23,532] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 49 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:57:23,532] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:57:23,532] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:242)
[2025-03-20 18:57:23,533] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:604)
[2025-03-20 18:57:23,534] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=23, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:665)
[2025-03-20 18:57:23,536] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=23, memberId='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:842)
[2025-03-20 18:57:23,536] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Joined group at generation 23 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056', leaderUrl='http://127.0.1.1:8083/', offset=49, connectorIds=[], taskIds=[], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2621)
[2025-03-20 18:57:23,536] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Starting connectors and tasks using config offset 49 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1959)
[2025-03-20 18:57:23,536] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1988)
[2025-03-20 18:57:25,662] INFO [0:0:0:0:0:0:0:1] - - [20/Mar/2025:17:57:25 +0000] "GET /connectors HTTP/1.1" 200 2 "-" "curl/8.5.0" 2 (org.apache.kafka.connect.runtime.rest.RestServer:62)
[2025-03-20 18:57:42,416] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:67)
[2025-03-20 18:57:42,416] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:354)
[2025-03-20 18:57:42,421] INFO Stopped http_8083@3265995e{HTTP/1.1, (http/1.1)}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector:383)
[2025-03-20 18:57:42,422] INFO node0 Stopped scavenging (org.eclipse.jetty.server.session:149)
[2025-03-20 18:57:42,425] INFO Stopped o.e.j.s.ServletContextHandler@771afdd5{/,null,STOPPED} (org.eclipse.jetty.server.handler.ContextHandler:1159)
[2025-03-20 18:57:42,425] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:383)
[2025-03-20 18:57:42,425] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder:841)
[2025-03-20 18:57:42,425] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Stopping connectors and tasks that are still assigned to this worker. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:798)
[2025-03-20 18:57:42,426] INFO Stopping KafkaBasedLog for topic connect-status (org.apache.kafka.connect.util.KafkaBasedLog:316)
[2025-03-20 18:57:42,426] INFO [Producer clientId=connect-cluster-statuses] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer:1373)
[2025-03-20 18:57:42,431] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:42,431] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,431] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,431] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:42,431] INFO App info kafka.producer for connect-cluster-statuses unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:42,431] INFO [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1055)
[2025-03-20 18:57:42,432] INFO [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1102)
[2025-03-20 18:57:42,555] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:42,555] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,556] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,556] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:42,559] INFO App info kafka.consumer for connect-cluster-statuses unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:42,560] INFO Stopped KafkaBasedLog for topic connect-status (org.apache.kafka.connect.util.KafkaBasedLog:340)
[2025-03-20 18:57:42,560] INFO Closing KafkaConfigBackingStore (org.apache.kafka.connect.storage.KafkaConfigBackingStore:405)
[2025-03-20 18:57:42,560] INFO Stopping KafkaBasedLog for topic connect-configs (org.apache.kafka.connect.util.KafkaBasedLog:316)
[2025-03-20 18:57:42,561] INFO [Producer clientId=connect-cluster-configs] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer:1373)
[2025-03-20 18:57:42,565] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:42,565] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,565] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:42,565] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:42,565] INFO App info kafka.producer for connect-cluster-configs unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:42,566] INFO [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1055)
[2025-03-20 18:57:42,566] INFO [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1102)
[2025-03-20 18:57:43,041] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,041] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,041] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,041] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,043] INFO App info kafka.consumer for connect-cluster-configs unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,043] INFO Stopped KafkaBasedLog for topic connect-configs (org.apache.kafka.connect.util.KafkaBasedLog:340)
[2025-03-20 18:57:43,043] INFO Closed KafkaConfigBackingStore (org.apache.kafka.connect.storage.KafkaConfigBackingStore:410)
[2025-03-20 18:57:43,043] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:249)
[2025-03-20 18:57:43,044] INFO Stopping KafkaOffsetBackingStore (org.apache.kafka.connect.storage.KafkaOffsetBackingStore:260)
[2025-03-20 18:57:43,044] INFO Stopping KafkaBasedLog for topic connect-offsets (org.apache.kafka.connect.util.KafkaBasedLog:316)
[2025-03-20 18:57:43,044] INFO [Producer clientId=connect-cluster-offsets] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer:1373)
[2025-03-20 18:57:43,047] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,047] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,047] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,047] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,047] INFO App info kafka.producer for connect-cluster-offsets unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,048] INFO [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1055)
[2025-03-20 18:57:43,048] INFO [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1102)
[2025-03-20 18:57:43,155] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,155] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,155] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,155] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,157] INFO App info kafka.consumer for connect-cluster-offsets unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,157] INFO Stopped KafkaBasedLog for topic connect-offsets (org.apache.kafka.connect.util.KafkaBasedLog:340)
[2025-03-20 18:57:43,157] INFO Stopped KafkaOffsetBackingStore (org.apache.kafka.connect.storage.KafkaOffsetBackingStore:262)
[2025-03-20 18:57:43,157] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,157] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,157] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,157] INFO App info kafka.connect for 127.0.1.1:8083 unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,158] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:270)
[2025-03-20 18:57:43,161] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Member connect-127.0.1.1:8083-583987df-efc5-4e09-ae38-b52425476056 sending LeaveGroup request to coordinator carlos-desktop:9092 (id: 2147483647 rack: null) due to the consumer is being closed (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:1173)
[2025-03-20 18:57:43,161] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:1055)
[2025-03-20 18:57:43,161] WARN [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Close timed out with 1 pending requests to coordinator, terminating client connections (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:1140)
[2025-03-20 18:57:43,161] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,161] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,161] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,163] INFO App info kafka.connect for connect-127.0.1.1:8083 unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,165] INFO App info kafka.admin.client for connect-cluster-shared-admin unregistered (org.apache.kafka.common.utils.AppInfoParser:88)
[2025-03-20 18:57:43,167] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:684)
[2025-03-20 18:57:43,167] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:688)
[2025-03-20 18:57:43,167] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:694)
[2025-03-20 18:57:43,167] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder:387)
[2025-03-20 18:57:43,168] INFO [Worker clientId=connect-127.0.1.1:8083, groupId=connect-cluster] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder:848)
[2025-03-20 18:57:43,168] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:72)
